spring:
  application:
    name: visitation-service
  datasource:
    url: jdbc:mysql://localhost:3306/EdirneGezgini-VisitationService
    username: root
    password: 35965132

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

application:
  security:
    jwt:
      secret-key: 8f3ca84c5122366a19f7804e71c432fc639c7817903321a43879fe8c436c2311
  service:
    accommodation-service: "http://localhost:9000/accommodation-service/api/"
    place-service: "http://localhost:9000/place-service/api/"
    restaurant-service: "http://localhost:9000/restaurant-service/api/"

server:
  port: 0