spring:
  application:
    name: place-service
  datasource:
    url: jdbc:mysql://localhost:3306/EdirneGezgini-PlaceService
    username: root
    password: 35965132

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


server:
  port: 54731
  servlet:
    context-path: /
