spring:
  application:
    name: accommodation-service
  datasource:
    url: jdbc:mysql://localhost:3306/EdirneGezgini-AccommodationService
    username: root
    password: 35965132

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#eureka:
#  client:
#    instance-info-replication-interval-seconds: 5
#    registry-fetch-interval-seconds: 5
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
application:
  security:
    jwt:
      secret-key: 8f3ca84c5122366a19f7804e71c432fc639c7817903321a43879fe8c436c2311

server:
  port: 54660
