spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/EdirneGezgini-UserService
    username: root
    password: 35965132

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


server:
  port: 54741
