spring:
  application:
    name: favorite-service
  datasource:
    url: jdbc:mysql://localhost:3306/EdirneGezgini-FavoriteService
    username: root
    password: 35965132

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

application:
  security:
    jwt:
      secret-key: 8f3ca84c5122366a19f7804e71c432fc639c7817903321a43879fe8c436c2311
  service:
    accommodation-service: "http://localhost:9000/accommodation-service/api/"
    place-service: "http://localhost:9000/place-service/api/"
    restaurant-service: "http://localhost:9000/restaurant-service/api/"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.springframework.boot: DEBUG
    org.springframework: INFO

server:
  port: 54707
  servlet:
    context-path: /
