spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:mysql://localhost:3306/EdirneGezgini-RestaurantService
    username: root
    password: 35965132

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 54623
  servlet:
    context-path: /
